### ISSUE TITLE
Product Lines are not saving even when all information is entered

### ISSUE THREAD

**Issue by kimcashwell** [FMTCco/app-fresh.press#19]
I had this complaint from an advertiser and went to try it out myself. She has 3 product lines created, and no campaign (since it won't save) and therefore no opportunities. 

I clicked "New" and entered the information:

<img width="1202" alt="screen shot 2018-05-18 at 12 39 08 pm" src="https://user-images.githubusercontent.com/24657284/40254472-7c63cdc0-5a98-11e8-90a5-488ff7ece8ca.png">

The page looked like it refreshed but nothing happened. I went back to my campaigns and nothing existed, just the button to create a new one.

**Comment by jamesvweston** [comment]
I just pushed a fix for campaigns and product lines. The page was working correctly in the sense that it didn't allow the user to save the items if they didn't have all the required fields, or if the fields had too many characters.
However, for some of the errors it wasn't actually displaying a message so the user didn't know what was going on. Improved validation messages and on screen notifications are now live.
