### ISSUE TITLE
Resolve Correct Influencer IDs

### ISSUE THREAD

**Issue by kimcashwell** [FMTCco/app-fresh.press#2]
The new marketplace is just not allowing us to view the ID associated with each unique influencer.

Example: Sand and Snow influencer ID should be 1332. When you search the user or search Sand and Snow, this ID does not show anywhere, however it is showing an ID of 1948. Not sure what this new ID number is. All of the influencer ID's no longer match up.

*Chrystal can provide more information on this if necessary.

**Comment by jamesvweston** [comment]
Kim,

This isn't a bug. The report you're looking at when you do this search is called the "Admin Users Report" so the emphasis is on the user. So if you see an Id field it is the user id. 
If you log in as that user and go to their spheres you see the sphere correctly labeled as 1332.
All of the influencer Id's match up correctly.

**Comment by kimcashwell** [comment]
Thanks Jimmy - I passed the instructions along to Chrystal, I'll let you know if she has any more issues with this.
