### ISSUE TITLE
Display information & allow saving new Product Line

### ISSUE THREAD

**Issue by kimcashwell** [FMTCco/app-fresh.press#6]
An advertiser is having difficulty creating a new product line. Once you fill out the information in the first 2 steps, the 3rd one doesn't display the "platforms" like it should. If you click "save", nothing happens.

Here's what happened to me when I tried it on the FPM account:

<img width="1204" alt="screen shot 2018-05-02 at 10 14 11 am" src="https://user-images.githubusercontent.com/24657284/39538458-c12a6c9c-4df1-11e8-8a99-14df67445162.png">

**Comment by jamesvweston** [comment]
This was a legitimate bug. When the product line was created for the first time the page would attempt to reload the product line that was just saved, which caused the page to break in the background.
Everything should be working now.
