### ISSUE TITLE
Make sure gig approval process is functioning correctly

### ISSUE THREAD

**Issue by kimcashwell** [FMTCco/app-fresh.press#7]
An advertiser (andrea@prepdish.com) was having trouble approving a gig. Here's what she said:

> "It is not letting me approve the status because it's still pending? It won't let me do anything basically. ... Nevermind...I had to enter a message, which btw, it didn't allow me to see what i was typing. that was hidden..."

I can probably ask her for more details if/when you need it... she didn't send a screenshot of the issue or anything.

**Comment by jamesvweston** [comment]
This is working correctly. If they accept the gig without a message it will display an error message letting them know that the message is required.
